baseURL = "https://binainsanstb.netlify.com/"
disableLanguages = ["fr-fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Memadukan kurikulum nasional dengan pendidikan berbasis Islam"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "teacher"
name = "teacher"
[[menu.footer]]
URL = "notice"
name = "notice"
[[menu.footer]]
URL = "event"
name = "event"
[[menu.footer]]
URL = "scholarship"
name = "scholarship"
[[menu.footer]]
URL = "research"
name = "research"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "course"
name = "course"
weight = 2
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 3
[[menu.main]]
URL = "teacher"
name = "teacher"
parent = "Pages"
[[menu.main]]
URL = "notice"
name = "notice"
parent = "Pages"
[[menu.main]]
URL = "event"
name = "event"
parent = "Pages"
[[menu.main]]
URL = "scholarship"
name = "scholarship"
parent = "Pages"
[[menu.main]]
URL = "research"
name = "research"
parent = "Pages"
[[menu.main]]
URL = "blog"
name = "blog"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Perum Panji Permai Blok AA 7-8"
author = "SDIT Bina Insan Situbondo"
contact_form_action = "#"
description = "This is meta description"
email = "binainsanstb@gmail.com"
google_analitycs_id = ""
logo = "images/logo.png"
mobile = "+211234565523"
top_header = true
[params.map]
enable = true
gmap_api = "https://goo.gl/maps/YK1Pic1eWGwiD4Wv6"
map_latitude = "-7.6878306"
map_longitude = "114.0330249,15"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
